-- V1: reference data (dropdowns + validation). See docs/DATA_MODEL.md.
-- Flyway runs this once per database and records it in flyway_schema_history. Never edit an applied
-- migration; add a new V2__..., V3__... instead.

-- Extensions used by later migrations: case-insensitive text (handles) and trigram fuzzy search.
-- Both are "trusted" extensions, so they also work on AWS RDS without superuser.
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- One city belongs to exactly one state. Custom cities are added here at runtime.
CREATE TABLE geo_city (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    state       text        NOT NULL,
    city        text        NOT NULL,
    is_custom   boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  text        NOT NULL DEFAULT 'system'
);
-- "Chandigarh" and "chandigarh" are the same city
CREATE UNIQUE INDEX geo_city_city_uq ON geo_city (lower(city));
CREATE INDEX geo_city_state_idx ON geo_city (state);

-- Categories and languages: built-in values plus custom ones added inline.
-- A CHECK constraint instead of a Postgres ENUM type: adding a value later is a one-line migration.
CREATE TABLE taxonomy (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type        text        NOT NULL CHECK (type IN ('CATEGORY', 'LANGUAGE')),
    value       text        NOT NULL,
    is_custom   boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  text        NOT NULL DEFAULT 'system'
);
CREATE UNIQUE INDEX taxonomy_type_value_uq ON taxonomy (type, lower(value));

-- Built-in data (generated from frontend/src/data/seed.ts so UI and DB match)
INSERT INTO geo_city (state, city) VALUES
('Andhra Pradesh', 'Visakhapatnam'),
('Andhra Pradesh', 'Vijayawada'),
('Andhra Pradesh', 'Guntur'),
('Andhra Pradesh', 'Nellore'),
('Andhra Pradesh', 'Kurnool'),
('Andhra Pradesh', 'Tirupati'),
('Andhra Pradesh', 'Kakinada'),
('Andhra Pradesh', 'Rajahmundry'),
('Andhra Pradesh', 'Anantapur'),
('Arunachal Pradesh', 'Itanagar'),
('Arunachal Pradesh', 'Naharlagun'),
('Arunachal Pradesh', 'Pasighat'),
('Arunachal Pradesh', 'Tawang'),
('Assam', 'Guwahati'),
('Assam', 'Silchar'),
('Assam', 'Dibrugarh'),
('Assam', 'Jorhat'),
('Assam', 'Tezpur'),
('Assam', 'Nagaon'),
('Bihar', 'Patna'),
('Bihar', 'Gaya'),
('Bihar', 'Bhagalpur'),
('Bihar', 'Muzaffarpur'),
('Bihar', 'Darbhanga'),
('Bihar', 'Purnia'),
('Chhattisgarh', 'Raipur'),
('Chhattisgarh', 'Bhilai'),
('Chhattisgarh', 'Bilaspur'),
('Chhattisgarh', 'Korba'),
('Chhattisgarh', 'Durg'),
('Goa', 'Panaji'),
('Goa', 'Margao'),
('Goa', 'Vasco da Gama'),
('Goa', 'Mapusa'),
('Gujarat', 'Ahmedabad'),
('Gujarat', 'Surat'),
('Gujarat', 'Vadodara'),
('Gujarat', 'Rajkot'),
('Gujarat', 'Bhavnagar'),
('Gujarat', 'Jamnagar'),
('Gujarat', 'Gandhinagar'),
('Gujarat', 'Anand'),
('Haryana', 'Gurugram'),
('Haryana', 'Faridabad'),
('Haryana', 'Panchkula'),
('Haryana', 'Ambala'),
('Haryana', 'Karnal'),
('Haryana', 'Panipat'),
('Haryana', 'Rohtak'),
('Haryana', 'Hisar'),
('Haryana', 'Sonipat'),
('Himachal Pradesh', 'Shimla'),
('Himachal Pradesh', 'Dharamshala'),
('Himachal Pradesh', 'Manali'),
('Himachal Pradesh', 'Mandi'),
('Himachal Pradesh', 'Solan'),
('Himachal Pradesh', 'Kullu'),
('Jharkhand', 'Ranchi'),
('Jharkhand', 'Jamshedpur'),
('Jharkhand', 'Dhanbad'),
('Jharkhand', 'Bokaro'),
('Karnataka', 'Bengaluru'),
('Karnataka', 'Mysuru'),
('Karnataka', 'Mangaluru'),
('Karnataka', 'Hubballi'),
('Karnataka', 'Belagavi'),
('Karnataka', 'Udupi'),
('Karnataka', 'Davanagere'),
('Kerala', 'Kochi'),
('Kerala', 'Thiruvananthapuram'),
('Kerala', 'Kozhikode'),
('Kerala', 'Thrissur'),
('Kerala', 'Kannur'),
('Kerala', 'Kollam'),
('Kerala', 'Alappuzha'),
('Madhya Pradesh', 'Indore'),
('Madhya Pradesh', 'Bhopal'),
('Madhya Pradesh', 'Gwalior'),
('Madhya Pradesh', 'Jabalpur'),
('Madhya Pradesh', 'Ujjain'),
('Madhya Pradesh', 'Sagar'),
('Maharashtra', 'Mumbai'),
('Maharashtra', 'Pune'),
('Maharashtra', 'Nagpur'),
('Maharashtra', 'Nashik'),
('Maharashtra', 'Thane'),
('Maharashtra', 'Navi Mumbai'),
('Maharashtra', 'Aurangabad'),
('Maharashtra', 'Kolhapur'),
('Maharashtra', 'Solapur'),
('Maharashtra', 'Amravati'),
('Manipur', 'Imphal'),
('Meghalaya', 'Shillong'),
('Meghalaya', 'Tura'),
('Mizoram', 'Aizawl'),
('Nagaland', 'Kohima'),
('Nagaland', 'Dimapur'),
('Odisha', 'Bhubaneswar'),
('Odisha', 'Cuttack'),
('Odisha', 'Rourkela'),
('Odisha', 'Puri'),
('Odisha', 'Sambalpur'),
('Punjab', 'Ludhiana'),
('Punjab', 'Amritsar'),
('Punjab', 'Jalandhar'),
('Punjab', 'Patiala'),
('Punjab', 'Mohali'),
('Punjab', 'Bathinda'),
('Punjab', 'Pathankot'),
('Punjab', 'Hoshiarpur'),
('Rajasthan', 'Jaipur'),
('Rajasthan', 'Jodhpur'),
('Rajasthan', 'Udaipur'),
('Rajasthan', 'Kota'),
('Rajasthan', 'Ajmer'),
('Rajasthan', 'Bikaner'),
('Rajasthan', 'Alwar'),
('Rajasthan', 'Jaisalmer'),
('Rajasthan', 'Pushkar'),
('Sikkim', 'Gangtok'),
('Tamil Nadu', 'Chennai'),
('Tamil Nadu', 'Coimbatore'),
('Tamil Nadu', 'Madurai'),
('Tamil Nadu', 'Tiruchirappalli'),
('Tamil Nadu', 'Salem'),
('Tamil Nadu', 'Tirunelveli'),
('Tamil Nadu', 'Vellore'),
('Tamil Nadu', 'Ooty'),
('Telangana', 'Hyderabad'),
('Telangana', 'Secunderabad'),
('Telangana', 'Warangal'),
('Telangana', 'Nizamabad'),
('Telangana', 'Karimnagar'),
('Tripura', 'Agartala'),
('Uttar Pradesh', 'Lucknow'),
('Uttar Pradesh', 'Noida'),
('Uttar Pradesh', 'Greater Noida'),
('Uttar Pradesh', 'Ghaziabad'),
('Uttar Pradesh', 'Kanpur'),
('Uttar Pradesh', 'Agra'),
('Uttar Pradesh', 'Varanasi'),
('Uttar Pradesh', 'Prayagraj'),
('Uttar Pradesh', 'Meerut'),
('Uttar Pradesh', 'Bareilly'),
('Uttar Pradesh', 'Aligarh'),
('Uttar Pradesh', 'Mathura'),
('Uttarakhand', 'Dehradun'),
('Uttarakhand', 'Haridwar'),
('Uttarakhand', 'Rishikesh'),
('Uttarakhand', 'Nainital'),
('Uttarakhand', 'Haldwani'),
('Uttarakhand', 'Mussoorie'),
('West Bengal', 'Kolkata'),
('West Bengal', 'Howrah'),
('West Bengal', 'Siliguri'),
('West Bengal', 'Durgapur'),
('West Bengal', 'Asansol'),
('West Bengal', 'Darjeeling'),
('Andaman and Nicobar Islands', 'Port Blair'),
('Chandigarh', 'Chandigarh'),
('Dadra and Nagar Haveli and Daman and Diu', 'Daman'),
('Dadra and Nagar Haveli and Daman and Diu', 'Silvassa'),
('Dadra and Nagar Haveli and Daman and Diu', 'Diu'),
('Delhi', 'Delhi'),
('Delhi', 'New Delhi'),
('Jammu and Kashmir', 'Srinagar'),
('Jammu and Kashmir', 'Jammu'),
('Jammu and Kashmir', 'Anantnag'),
('Jammu and Kashmir', 'Baramulla'),
('Ladakh', 'Leh'),
('Ladakh', 'Kargil'),
('Lakshadweep', 'Kavaratti'),
('Puducherry', 'Puducherry'),
('Puducherry', 'Karaikal');

INSERT INTO taxonomy (type, value) VALUES
('CATEGORY', 'Jewellery'),
('CATEGORY', 'Fashion'),
('CATEGORY', 'Beauty'),
('CATEGORY', 'Food'),
('CATEGORY', 'Fitness'),
('CATEGORY', 'Travel'),
('CATEGORY', 'Lifestyle'),
('CATEGORY', 'Tech'),
('CATEGORY', 'Parenting'),
('LANGUAGE', 'Hindi'),
('LANGUAGE', 'English'),
('LANGUAGE', 'Punjabi'),
('LANGUAGE', 'Marathi'),
('LANGUAGE', 'Bengali'),
('LANGUAGE', 'Tamil'),
('LANGUAGE', 'Telugu'),
('LANGUAGE', 'Gujarati'),
('LANGUAGE', 'Kannada'),
('LANGUAGE', 'Malayalam'),
('LANGUAGE', 'Odia'),
('LANGUAGE', 'Urdu'),
('LANGUAGE', 'Assamese'),
('LANGUAGE', 'Rajasthani'),
('LANGUAGE', 'Haryanvi'),
('LANGUAGE', 'Bhojpuri'),
('LANGUAGE', 'Maithili'),
('LANGUAGE', 'Konkani'),
('LANGUAGE', 'Tulu'),
('LANGUAGE', 'Kashmiri'),
('LANGUAGE', 'Dogri'),
('LANGUAGE', 'Sindhi'),
('LANGUAGE', 'Nepali'),
('LANGUAGE', 'Manipuri'),
('LANGUAGE', 'Bodo'),
('LANGUAGE', 'Santali'),
('LANGUAGE', 'Sanskrit');
